apiVersion : apps/v1
kind: Deployment
metadata:
  name: "votingkubecluster-ab2a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "votingkubecluster-ab2a"
  template:
    metadata:
      labels:
        app: "votingkubecluster-ab2a"
    spec:
      containers:
        - name: "votingkubecluster-ab2a"
          image: "votingdocker.azurecr.io/votingkubecluster"
          ports:
          - containerPort: 80